### ISSUE TITLE
[FUNCTIONAL] Cannot make makefile file in Linux

### ISSUE THREAD

**Issue by KiraTodorova** [Kagamma/satania-buddy#13]
Description:

I tried to install the dependencies but after installing the required dependencies to run the makefile, the make install run command returns an error  Error: (lazerus) invalid Lazarus directory  "": directory lcl not found

Steps to reproduce:

1. Extract .zip file
2. install all dependencies required to run the makefile
3. cd inside the downloaded folder
4. Run the command: sudo make
5. Observe the result!

Expected result:

The user can compile the makefile

Actual result:

The user gets: 
Error: (lazerus) invalid Lazarus directory  "": directory lcl not found

Notes:

OS: Linux Manjaro KDE Plasma, Arch
Version: Latest (aka installed the same date as this report was created)

Workaround: Tried to symlink lcl to /usr/local/lib/fpc/3.1.1/units/x86_64-linux/* but it gave the same error.

**Comment by Kagamma** [comment]
I haven't checked with Lazarus version from Arch repo. The app is made with FPC + Lazarus trunk version in mind so you may want to build FPC and Lazarus directly from source code instead.

A nice tutorial shows how to build FPC + Lazarus from source: https://www.youtube.com/watch?v=Snf0xgdREOQ

A side node: You will need to remove `lazactivex` from project dependencies before building `satania-buddy` on Linux. It's required for Windows only and there's no way to tell Lazarus to exclude this dependency for Linux build (and I don't want to maintain 2 project files).

**Comment by Kagamma** [comment]
Steps to build the app is documented here: https://github.com/Kagamma/satania-buddy/wiki/How-to-build-the-app-from-source-code
